apiVersion: apps/v1
kind: Deployment
metadata:
  
  labels:
    app: currency-conversion
  name: currency-conversion
 
spec:
 
  replicas: 1
  
  selector:
    matchLabels:
      app: currency-conversion
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
        - name: currency-conversion
          image: imadmin1992/currency-conversion:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8100
          env:
            env:
              - name: JAVA_TOOL_OPTIONS
                value: "-Deureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka -Deureka.instance.preferIpAddress=true"

              - name: SPRING_CONFIG_IMPORT
                value: "optional:configserver:http://config-server:8888"
               

