apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
         - name: currency-exchange
           image: imadmin1992/currency-exchange:latest
           imagePullPolicy: Always
           ports:
             - containerPort: 8000
           env:
             - name: JAVA_TOOL_OPTIONS
               value: "-Deureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka"

             - name: SPRING_CONFIG_IMPORT
               value: "optional:configserver:http://config-server:8888"