apiVersion: apps/v1
kind: Deployment

metadata:
  name: config-server
  labels:
    app: config-server

spec:
  replicas: 1

  selector:
    matchLabels:
      app: config-server

  template:
    metadata:
      labels:
        app: config-server

    spec:
      containers:
        - name: config-server
          image: imadmin1992/config-server:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8888

          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: https://github.com/hussainali92/FirstMicroservicesProject.git

            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS
              value: git-localconfigserver-repo-prob

            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
              value: master

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://naming-server:8761/eureka